[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "cacert",
  "glib",
  "dbus",
  "atk",
  "cups",
  "libdrm",
  "expat",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libXcursor",
  "libxkbcommon",
  "pango",
  "cairo",
  "alsa-lib",
]

[phases.install]
cmds = ["npm ci", "npx prisma generate"]

[phases.build]
cmds = ["npx tsc"]

[start]
cmd = "npx prisma migrate deploy && node dist/index.js"
